CREATE TABLE parts (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE,
	quantity INT NOT NULL CHECK (quantity >= 0),
	active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE part_locations (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	part_id BIGINT NOT NULL REFERENCES parts (id) ON DELETE CASCADE,
	location VARCHAR(255) NOT NULL,
	UNIQUE (part_id, location)
);
