CREATE TABLE projects (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE bom_lines (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	project_id BIGINT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
	part_id BIGINT NOT NULL REFERENCES parts (id) ON DELETE RESTRICT,
	quantity_per_unit INT NOT NULL CHECK (quantity_per_unit > 0),
	UNIQUE (project_id, part_id)
);

CREATE TABLE project_links (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	project_id BIGINT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
	url VARCHAR(2048) NOT NULL CHECK (url ~* '^https?://'),
	label VARCHAR(255)
);
